### ISSUE TITLE
Writing a new driver

### ISSUE THREAD

**Issue by moxious** [db-migrate/english-docs#11]
I'm considering writing a new driver to support couchbase and ottoman.

I looked at the SQL and NoSQL API here: https://db-migrate.readthedocs.io/en/latest/API/NoSQL/  and some of these concepts don't really apply.  For example, the NoSQL API contains methods such as createCollection and renameCollection, which would be foreign to people using Couchbase, but fits in perfectly with the existing MongoDB driver.

What would project advice be in this situation?  Make my own API that makes sense for the DB I'm trying to migrate?  Extend the API?  Or just go my own route with this plugin?

I've worked with many other databases of different sorts like Redis and Neo4j, and drivers for those would have the same troubles.  There may not be any set of abstractions that's reasonably consistent to "NoSQL databases".

**Comment by wzrdtales** [comment]
@moxious You're right, `renameCollection` and so on are mongodb specific, thus yes you will have to provide your own documentation and the current docs are most likely to be changed in some future (PRs are welcome though ;) ).

So to give you the direction:
Make your own API specific to the db, but try to implement all SQL methods from the default API and put them into a context that makes sense. In the example of mongodb `createCollection` is the `createTable` pendant.

If you have ideas how we may restructure the docs, you're welcome to go into discussion concerning this.

If you have any other question don't hesitate to ask :)

**Comment by moxious** [comment]
OK -- so the answer is to implement the SQL API with stuff that makes sense (that's reasonable) but don't worry about implementing the Mongo methods, which don't make a whole lot of sense.  I can work with that.

On restructuring the docs, I don't know that they need restructuring per se, I would just suggest that the project not present the mongo driver's API as "the official NoSQL API"  This guidance you're giving me is eminently reasonable, maybe just reflect that same in the docs.

It may take me a few weeks on other prep work, but we need this for couchbase so I'm almost desitined to write it. Thanks for the help.
